name: HopeofGlory
favicon: null
layout_spectrum: 0.7526529291644692
typography_spectrum: 0.18414310552179813
title: Hope of Glory Ministries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.30655297287739813
  lightness: 0.1304383110255003
  saturation: 0.775622331071645
  rhythmicContrast: 0.4555936874821782
purpose: []
